### PR TITLE
development environments

### PR DESCRIPTION
**Pull request by Dieterbe**

### CODE REVIEW

**Comment by rolandgeider** [comment]
careful with moving the prod compose to its own sub folder, the names of the docker volumes are <container_name> prefixed with <name of folder> so moving this would seeminly reset all installations, I would just leave that compose file in root.

Also like we talked on discord, we should do something about the config file(s), but that can be done later.

**Comment by Dieterbe** [comment]
> careful with moving the prod compose to its own sub folder, the names of the docker volumes are <container_name> prefixed with so moving this would seeminly reset all installations, I would just leave that compose file in root.

This shouldn't cause an issue, precisely because as you say, volumes and containers are given names (and stored in a path) that are independent of where you run them from.  That said it's worth trying to confirm. I'm not on my pc but I can try later. The postgres-data would be a good one to try it with right ?

**Comment by Dieterbe** [comment]
Ah your syntax got swallowed a bit but now I see what you mean. According to https://docs.docker.com/compose/environment-variables/envvars/#compose_project_name we can set a custom name, so we can set one that matches the previous directory name, although I suppose people could have checked out this repo in a dir with any name of their choosing 🤔

**Comment by rolandgeider** [comment]
yes exactly, we don't know where people checked this out (plus it makes that the "main" compose file)

**Pull request merged**
