### PR TITLE
+ Simplified docker-compose project structure to two directories (dat…

### PR DESCRIPTION
**Pull request by AlexAshs**
+ Simplified docker-compose project structure to two directories (data & config)
- Removed docker named volumes in faver for bind volumes, which do persist data on disk, which simplifies backups and migrations
+ Named all containers for simpler deployment via ansible
+ Added healthchecks to all containers

For the server container's healthcheck to function, wget, or if preferred curl, needs to be installed in the docker image, however I did not see the proper place to submit that request.

### CODE REVIEW

**Comment by rolandgeider** [comment]
Thanks for the PR! Not having to build the nginx image and healthchecks are great (I can install wget in the base image). As for renaming the containers, does this have some impact for people that are using the old config? The same for the binds, the data would then be gone

**Comment by AlexAshs** [comment]
Thank you for your positive feedback, that is greatly appreciated.
I forgot to mention, that the Dockerfile is not needed anymore.

This certainly has an impact on people. who change their docker-compose.yml without bringing the project down first, because now the containers do have different names, but docker-compose is not notified of that change.

However I believe, this will only benefit people in the future, because explicit trumps implicit.

As for the volumes:

They can be made persistent, by adding some options to the named volumes, such as this:
`
dbdata:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/web
      o: bind
`
This way already existing data is not lost and will be accessible on the disk.

The way I wrote it seemed a bit cleaner, because it takes up less space, but if this is preferred, I can change it using named volumes.

**Comment by rolandgeider** [comment]
oh yes, explicit is definitely better. I'd leave the named volumes, I feel that would be too disruptive right now, but we can live with the fact that if the docker-compose is updated before shutting down some containers will keep running, I can write an announcement just in case (for whoever reads those 😅 )

**Comment by AlexAshs** [comment]
Excellent, I will change the volumes to named, but bind mounted volumes.

As for the announcement:
If someone should forget to bring the docker-compose project down first, this command should suffice:
```
docker-compose up -d --remove-orphans
```

**Comment by rolandgeider** [comment]
Sorry, I meant to leave the volumes as real volumes, not bind volumes

**Comment by AlexAshs** [comment]
Little miscommunication, no problem.
Fixed it.

**Comment by rolandgeider** [comment]
Alright, I'll try to find some time the next days to give this a spin

**Comment by AlexAshs** [comment]
No worries, we've all got jobs, so take your time.

**Pull request merged**
